/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Liveness probe
         * @description Returns 200 when the process is up. Does not check dependencies.
         */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/readyz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Readiness probe
         * @description Returns 200 when Postgres and Redis are reachable.
         */
        get: operations["readyz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaceSignIn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaceSignInStart"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/request-push-verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaceSignInRequestPushVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/resend-push-verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaceSignInResendPushVerify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/request-sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaceSignInRequestSms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/verify-sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaceSignInVerifySms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/verify-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["workspaceSignInVerifyLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/request-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaceSignInRequestOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/verify-phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaceSignInVerifyPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaceSignInComplete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/request-delegate-push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Ask family keeper to approve device for sign-in */
        post: operations["workspaceSignInRequestDelegatePush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/delegate-details": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read-only delegate request details (no side effects) */
        get: operations["workspaceSignInDelegateDetails"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/delegate-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Deep link landing (read-only; may redirect to app) */
        get: operations["workspaceSignInDelegateLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/approve-delegate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Keeper approves delegate sign-in (authenticated) */
        post: operations["workspaceSignInApproveDelegate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/reject-delegate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaceSignInRejectDelegate"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/sign-in/delegate-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Waiting member polls delegation outcome */
        get: operations["workspaceSignInDelegateStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/personal/sign-in/request-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request OTP on verified personal email */
        post: operations["personalSignInRequestEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/personal/sign-in/verify-email": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["personalSignInVerifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/personal/sign-in/request-phone-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["personalSignInRequestPhoneOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/personal/sign-in/verify-phone": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["personalSignInVerifyPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/personal/sign-in/complete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["personalSignInComplete"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/sign-in/email/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @deprecated */
        post: operations["personalSignInRequestEmailLegacy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/recovery/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request account recovery via family keeper */
        post: operations["recoveryRequest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/recovery/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Confirm recovery with SMS code and set new password */
        post: operations["recoveryConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pair/phone/request-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pairPhoneRequestOTP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pair/phone/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pairPhoneVerifyOTP"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/devices/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Register push token (gateway → notification-service)
         * @description Public gateway route. Accepts device registration JWT (scope device_register) or family access JWT.
         *     Proxied to notification-service with service credentials.
         */
        post: operations["gatewayRegisterDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/devices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDevices"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/devices/{clientDeviceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["revokeDevice"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/workspace/password/change": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["workspaceChangePassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/email/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardingRequestEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/email/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardingVerifyEmail"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/email/verify-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Verify email via magic link token
         * @description Returns JSON by default (`Accept: application/json`).
         *     With `redirect=true` or `Accept: text/html`, responds with HTTP 302 to
         *     `ONBOARDING_APP_DEEP_LINK_BASE` (default `carelink://onboarding/verify-email`)
         *     including `onboardingChallengeId`, `familyId`, `workspaceSlug`, `workspaceEmail`, `status`.
         */
        get: operations["onboardingVerifyEmailLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/phone/request-otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardingRequestPhoneOtp"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/phone/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardingVerifyPhone"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/device/verify/request-push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardingDeviceVerifyRequestPush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/device/verify/resend-push": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardingDeviceVerifyResendPush"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/device/verify/request-sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardingDeviceVerifyRequestSms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/device/verify/verify-sms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardingDeviceVerifyVerifySms"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/device/verify-link": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["onboardingDeviceVerifyLink"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/device/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardingConfirmDevice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/password/setup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardingSetupPassword"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/onboarding/workspace/finalize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["onboardingFinalizeWorkspace"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/token/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["tokenRefresh"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pair/resolve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pairResolve"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pair/confirm": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pairConfirm"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pair/approval-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["pairApprovalStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pair/reject": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Reject join request (keeper via service token or family access JWT) */
        post: operations["pairReject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/pair/approve": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Approve join request (keeper via service token or family access JWT) */
        post: operations["pairApprove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateMe"];
        trace?: never;
    };
    "/user/me/avatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Upload avatar (stub CDN URL in MVP) */
        post: operations["uploadAvatar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create family (family-service)
         * @description After phone register the client may have only `userRefresh` (no family access JWT yet).
         *     Send `X-User-Refresh` instead of Bearer, or use Bearer when a family access token is available.
         */
        post: operations["createFamily"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/user/families": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List user families (family-service) */
        get: operations["listUserFamilies"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RecoveryRequestBody: {
            familySlug: string;
            /** @description E.164 phone number */
            phone: string;
        };
        RecoveryAcceptedResponse: {
            accepted: boolean;
            message: string;
        };
        RecoveryConfirmRequest: {
            /** Format: uuid */
            requestId: string;
            code: string;
            newPassword: string;
            phone: string;
            deviceId: string;
        };
        DelegatePushRequest: {
            challengeId: string;
            deviceId: string;
        };
        ApproveDelegateRequest: {
            token: string;
        };
        ApproveDelegateResponse: {
            approved?: boolean;
            challengeId?: string;
            deviceSession?: string;
        };
        PairPhoneRequestOTPRequest: {
            phone: string;
        };
        PairPhoneVerifyRequest: {
            phone: string;
            code: string;
        };
        PairPhoneVerifyResponse: {
            verified?: boolean;
            registrationToken?: string;
        };
        GatewayDeviceRegisterRequest: {
            /** @enum {string} */
            platform: "ios" | "android" | "web";
            clientDeviceId: string;
            /** @description Push token (optional for web) */
            token?: string;
        };
        ErrorResponse: {
            /** @enum {string} */
            code: "INVALID_CREDENTIALS" | "UNAUTHORIZED" | "TOKEN_EXPIRED" | "INVALID_OTP" | "PHONE_REGISTERED" | "SMS_UNDELIVERED" | "EMAIL_TAKEN" | "WEAK_PASSWORD" | "INVALID_PAIR_CODE" | "PAIR_SESSION_EXPIRED" | "PAIR_SESSION_NOT_FOUND" | "OFFLINE" | "RATE_LIMIT" | "UNKNOWN" | "PAIRING_SESSION_UNSUPPORTED" | "TEMP_PASSWORD_EXPIRED" | "WORKSPACE_NOT_FOUND" | "BAD_REQUEST" | "NOT_IMPLEMENTED" | "KEEPER_NOT_FOUND";
            message?: string;
        };
        OtpRequest: {
            /** @example +79001234567 */
            phone: string;
        };
        OtpRequestResponse: {
            /** @constant */
            sent: true;
            /** @enum {string} */
            channel: "sms";
        };
        OtpVerifyRequest: {
            phone: string;
            /** @example 1234 */
            code: string;
        };
        OtpVerifyResponse: {
            /** @constant */
            verified: true;
            registrationToken: string;
        };
        PhoneRegisterRequest: {
            registrationToken: string;
            displayName?: string;
            unionRole?: components["schemas"]["UnionRole"];
        };
        PhoneRegisterResponse: {
            /** Format: uuid */
            userId: string;
            userRefresh: string;
        };
        PhoneRegisterCompleteRequest: {
            registrationToken: string;
            displayName?: string;
            familyName: string;
            unionRole?: components["schemas"]["UnionRole"];
        };
        WorkspaceSignInRequest: {
            workspaceEmail: string;
            password: string;
            deviceId: string;
        };
        WorkspaceSignInResponse: {
            /** @enum {string} */
            flow: "shortcut" | "full";
            challengeId?: string;
            requiresPasswordChange?: boolean;
            /** @enum {string} */
            verificationChannel?: "push" | "sms";
            session?: components["schemas"]["AuthSessionResponse"];
        };
        DeviceVerifySentResponse: {
            sent?: boolean;
        };
        DeviceVerifySessionResponse: {
            deviceSession?: string;
            verified?: boolean;
            challengeId?: string;
            userId?: string;
            clientDeviceId?: string;
        };
        DeviceVerifyChallengeRequest: {
            challengeId: string;
            deviceId: string;
        };
        DeviceVerifySmsRequest: components["schemas"]["DeviceVerifyChallengeRequest"] & {
            phone: string;
        };
        DeviceVerifySmsConfirmRequest: components["schemas"]["DeviceVerifySmsRequest"] & {
            code: string;
        };
        OnboardingDeviceVerifyRequest: {
            onboardingChallengeId: string;
            userId: string;
            deviceId: string;
        };
        OnboardingDeviceVerifySmsRequest: components["schemas"]["OnboardingDeviceVerifyRequest"] & {
            phone: string;
        };
        OnboardingDeviceVerifySmsConfirmRequest: components["schemas"]["OnboardingDeviceVerifySmsRequest"] & {
            code: string;
        };
        OnboardingDeviceVerifyLinkResponse: components["schemas"]["DeviceVerifySessionResponse"] & {
            onboardingChallengeId?: string;
        };
        DeviceListResponse: {
            devices?: components["schemas"]["DeviceListItem"][];
        };
        DeviceListItem: {
            clientDeviceId?: string;
            platform?: string;
            lastSeenAt?: string;
            trusted?: boolean;
            active?: boolean;
        };
        WorkspaceSignInStartRequest: {
            workspaceEmail: string;
            deviceId: string;
        };
        WorkspaceSignInStartResponse: {
            /** @enum {string} */
            flow: "full";
            challengeId: string;
            displayName: string;
        };
        WorkspaceSignInRequestOtpRequest: {
            challengeId: string;
            phone: string;
        };
        WorkspaceSignInRequestOtpResponse: {
            sent: boolean;
        };
        WorkspaceSignInVerifyPhoneRequest: {
            challengeId: string;
            phone: string;
            code: string;
        };
        WorkspaceSignInVerifyPhoneResponse: {
            phoneVerified: boolean;
        };
        WorkspaceSignInCompleteRequest: {
            challengeId: string;
            password: string;
            deviceId: string;
        };
        WorkspaceSignInCompleteResponse: {
            requiresPasswordChange: boolean;
            session?: components["schemas"]["AuthSessionResponse"];
        };
        WorkspaceDelegateTokenRequest: {
            token: string;
        };
        WorkspaceDelegateDetailsResponse: {
            memberDisplayName: string;
            familyName: string;
            clientDeviceId: string;
            /** Format: date-time */
            requestedAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        WorkspaceDelegateApproveResponse: {
            approved: boolean;
            challengeId: string;
        };
        WorkspaceDelegateRejectResponse: {
            rejected: boolean;
            challengeId: string;
        };
        WorkspaceDelegateStatusResponse: {
            /** @enum {string} */
            status: "pending" | "approved" | "rejected" | "expired";
            /** @description Present only for the waiting member when status is approved */
            deviceSession?: string;
        };
        WorkspaceChangePasswordRequest: {
            challengeId?: string;
            /** Format: uuid */
            familyId?: string;
            /** Format: uuid */
            userId?: string;
            oldPassword: string;
            newPassword: string;
            deviceId: string;
        };
        OnboardingSentResponse: {
            sent: boolean;
        };
        OnboardingRequestEmailRequest: {
            /** Format: email */
            email: string;
        };
        OnboardingVerifyEmailRequest: {
            /** Format: email */
            email: string;
            /** @description Email OTP in XXX-XXX or XXXXXX form */
            code: string;
        };
        OnboardingVerifyEmailResponse: {
            onboardingChallengeId: string;
            /** Format: uuid */
            familyId: string;
            workspaceSlug: string;
            workspaceEmail: string;
            status: string;
        };
        OnboardingRequestPhoneOtpRequest: {
            onboardingChallengeId: string;
            phone: string;
        };
        OnboardingVerifyPhoneRequest: {
            onboardingChallengeId: string;
            phone: string;
            code: string;
            displayName?: string;
        };
        OnboardingVerifyPhoneResponse: {
            /** Format: uuid */
            userId: string;
            onboardingChallengeId: string;
            /** @description true when phone was already registered (second workspace onboarding) */
            existingUser: boolean;
            deviceRegistrationRequired: boolean;
            /** Format: date-time */
            userCreatedAt: string;
        };
        OnboardingConfirmDeviceRequest: {
            onboardingChallengeId: string;
            /** Format: uuid */
            userId: string;
            deviceId: string;
        };
        OnboardingConfirmDeviceResponse: {
            userRefresh: string;
            requiresPasswordSetup: boolean;
            onboardingChallengeId: string;
            /** Format: date-time */
            userCreatedAt: string;
        };
        OnboardingSetupPasswordRequest: {
            onboardingChallengeId: string;
            newPassword: string;
            deviceId: string;
        };
        OnboardingSetupPasswordResponse: {
            session: components["schemas"]["AuthSessionResponse"];
            requiresWorkspaceFinalize: boolean;
        };
        OnboardingFinalizeWorkspaceRequest: {
            onboardingChallengeId: string;
            workspaceSlug: string;
            displayName: string;
        };
        OnboardingFinalizeWorkspaceResponse: {
            workspaceSlug: string;
            workspaceEmail: string;
            displayName: string;
        };
        TokenRefreshRequest: {
            refresh: string;
        };
        UserRefreshResponse: {
            userRefresh: string;
        };
        LogoutRequest: {
            refresh?: string;
            /** @default false */
            allDevices: boolean;
        };
        OkResponse: {
            /** @constant */
            ok: true;
        };
        FamilyTokenBundle: {
            /** Format: uuid */
            familyId: string;
            access: string;
            refresh: string;
            /**
             * Format: int64
             * @description Unix timestamp milliseconds
             */
            expiresAt: number;
        };
        AuthSessionResponse: {
            /** Format: uuid */
            defaultFamilyId: string;
            userRefresh: string;
            families: components["schemas"]["FamilyTokenBundle"][];
        };
        PairResolveRequest: {
            /** Format: uuid */
            sessionId: string;
        };
        PairingResolveResult: {
            /** Format: uuid */
            sessionId: string;
            familyName: string;
            memberCount: number;
            slotLabel: string;
            roleLabel: string;
            trustTier: components["schemas"]["TrustTier"];
        };
        PairConfirmRequest: {
            /** Format: uuid */
            sessionId: string;
            code: string;
            name: string;
            /** @description Email path (with password) */
            email?: string;
            /** @description Email path (with email) */
            password?: string;
            /** @description Phone path after OTP verify */
            registrationToken?: string;
            unionRole?: components["schemas"]["UnionRole"];
        } & (unknown | unknown);
        PairConfirmPending: {
            /** @enum {string} */
            status: "pending";
            /** Format: uuid */
            requestId: string;
            /** @description Capability token for approval-status polling and GraphQL subscription (single use issued at confirm) */
            approvalSecret: string;
        };
        ApprovalStatusRequest: {
            /** Format: uuid */
            requestId: string;
            approvalSecret: string;
        };
        ApprovalPending: {
            /** @enum {string} */
            status: "pending";
        };
        ApprovalApproved: components["schemas"]["AuthSessionResponse"] & {
            /** @enum {string} */
            status: "approved";
        };
        ApprovalRejected: {
            /** @enum {string} */
            status: "rejected";
        };
        PairRejectRequest: {
            /** Format: uuid */
            requestId: string;
        };
        UpdateMeRequest: {
            displayName?: string;
        };
        UserProfile: {
            /** Format: uuid */
            userId: string;
            displayName: string;
            /**
             * Format: uri
             * @description Placeholder stub URL until S3/Blob storage (AUTH-014)
             */
            avatarUrl?: string;
        };
        CreateFamilyRequest: {
            name: string;
            unionRole?: components["schemas"]["UnionRole"];
        };
        CreateFamilyResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            memberCount: number;
            session: components["schemas"]["AuthSessionResponse"];
        };
        FamilyListResponse: {
            items: components["schemas"]["FamilyContext"][];
            total: number;
            hasMore: boolean;
            page: number;
            /** Format: date-time */
            serverTime: string;
        };
        FamilySyncResponse: {
            upserted: components["schemas"]["FamilyContext"][];
            removed: string[];
            /** Format: date-time */
            until: string;
        };
        FamilyContext: {
            /** Format: uuid */
            id: string;
            name: string;
            memberCount: number;
            role: string;
            harmonyIndex: number;
            isSetupComplete: boolean;
            pulseLabel: string;
            isOwner?: boolean;
            /** @enum {string} */
            familyType?: "core" | "kin";
            /** @enum {string} */
            syncStatus?: "synced" | "pending" | "isolated";
        };
        /** @enum {string} */
        UnionRole: "keeper" | "partner" | "parent";
        /** @enum {string} */
        TrustTier: "nuclear" | "kin" | "friend" | "advisor" | "guest";
    };
    responses: {
        /** @description Error */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Rate limited */
        RateLimit: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Feature disabled */
        NotImplemented: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        XScope: string;
        XDeviceSession: string;
        XDeviceId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Process healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ok */
                        status: string;
                    };
                };
            };
        };
    };
    readyz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Ready to serve traffic */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example ready */
                        status: string;
                    };
                };
            };
            /** @description Dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example not_ready */
                        status?: string;
                        postgres?: string;
                        redis?: string;
                    };
                };
            };
        };
    };
    workspaceSignIn: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceSignInRequest"];
            };
        };
        responses: {
            /** @description Shortcut session or full-flow challenge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSignInResponse"];
                };
            };
        };
    };
    workspaceSignInStart: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceSignInStartRequest"];
            };
        };
        responses: {
            /** @description Full-flow challenge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSignInStartResponse"];
                };
            };
        };
    };
    workspaceSignInRequestPushVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceVerifyChallengeRequest"];
            };
        };
        responses: {
            /** @description Device verify push dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceVerifySentResponse"];
                };
            };
        };
    };
    workspaceSignInResendPushVerify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceVerifyChallengeRequest"];
            };
        };
        responses: {
            /** @description Device verify push resent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceVerifySentResponse"];
                };
            };
        };
    };
    workspaceSignInRequestSms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceVerifySmsRequest"];
            };
        };
        responses: {
            /** @description Opt-in SMS dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceVerifySentResponse"];
                };
            };
        };
    };
    workspaceSignInVerifySms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeviceVerifySmsConfirmRequest"];
            };
        };
        responses: {
            /** @description SMS verified; device session issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceVerifySessionResponse"];
                };
            };
        };
    };
    workspaceSignInVerifyLink: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deep link verified; device session issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceVerifySessionResponse"];
                };
            };
        };
    };
    workspaceSignInRequestOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceSignInRequestOtpRequest"];
            };
        };
        responses: {
            /** @description OTP dispatched to registered phone */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSignInRequestOtpResponse"];
                };
            };
        };
    };
    workspaceSignInVerifyPhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceSignInVerifyPhoneRequest"];
            };
        };
        responses: {
            /** @description Phone bound to challenge */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSignInVerifyPhoneResponse"];
                };
            };
        };
    };
    workspaceSignInComplete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceSignInCompleteRequest"];
            };
        };
        responses: {
            /** @description Session or password change required */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceSignInCompleteResponse"];
                };
            };
        };
    };
    workspaceSignInRequestDelegatePush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Push dispatched to keeper */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description DELEGATE_NOT_ALLOWED */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaceSignInDelegateDetails: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Delegate context for keeper UI */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDelegateDetailsResponse"];
                };
            };
            /** @description DELEGATE_EXPIRED */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaceSignInDelegateLink: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JSON details when Accept prefers application/json */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDelegateDetailsResponse"];
                };
            };
            /** @description Redirect to app delegate screen when Accept includes text/html */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaceSignInApproveDelegate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceDelegateTokenRequest"];
            };
        };
        responses: {
            /** @description Approved (deviceSession is not returned to keeper) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDelegateApproveResponse"];
                };
            };
            /** @description UNAUTHORIZED */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description NOT_FOUND (wrong keeper or unknown request) */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description CONFLICT (token already used) */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    workspaceSignInRejectDelegate: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceDelegateTokenRequest"];
            };
        };
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDelegateRejectResponse"];
                };
            };
        };
    };
    workspaceSignInDelegateStatus: {
        parameters: {
            query: {
                challengeId: string;
                deviceId: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description pending | approved | rejected | expired */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorkspaceDelegateStatusResponse"];
                };
            };
        };
    };
    personalSignInRequestEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OTP dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Personal sign-in disabled (PERSONAL_SIGNIN_ENABLED=false) */
            501: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    personalSignInVerifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Email verified; challenge issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    personalSignInRequestPhoneOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phone OTP dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    personalSignInVerifyPhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Phone verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    personalSignInComplete: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    personalSignInRequestEmailLegacy: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Legacy path; prefer /auth/personal/sign-in/request-email */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    recoveryRequest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryRequestBody"];
            };
        };
        responses: {
            /** @description Opaque ticket (always returned to prevent enumeration) */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RecoveryAcceptedResponse"];
                };
            };
            501: components["responses"]["NotImplemented"];
        };
    };
    recoveryConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RecoveryConfirmRequest"];
            };
        };
        responses: {
            /** @description Full session after password reset */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
            /** @description Recovery code consumed or expired */
            410: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    pairPhoneRequestOTP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairPhoneRequestOTPRequest"];
            };
        };
        responses: {
            /** @description OTP dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        sent?: boolean;
                    };
                };
            };
        };
    };
    pairPhoneVerifyOTP: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairPhoneVerifyRequest"];
            };
        };
        responses: {
            /** @description Registration token for pair confirm */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairPhoneVerifyResponse"];
                };
            };
        };
    };
    gatewayRegisterDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GatewayDeviceRegisterRequest"];
            };
        };
        responses: {
            /** @description Device registered */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** Format: uuid */
                        deviceId?: string;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    listDevices: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Registered devices for current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceListResponse"];
                };
            };
        };
    };
    revokeDevice: {
        parameters: {
            query?: never;
            header: {
                "X-Device-Session": components["parameters"]["XDeviceSession"];
                "X-Device-Id": components["parameters"]["XDeviceId"];
            };
            path: {
                clientDeviceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Device revoked */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example revoked */
                        status?: string;
                    };
                };
            };
        };
    };
    workspaceChangePassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WorkspaceChangePasswordRequest"];
            };
        };
        responses: {
            /** @description Session after password change */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthSessionResponse"];
                };
            };
        };
    };
    onboardingRequestEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequestEmailRequest"];
            };
        };
        responses: {
            /** @description Verification email dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingSentResponse"];
                };
            };
        };
    };
    onboardingVerifyEmail: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingVerifyEmailRequest"];
            };
        };
        responses: {
            /** @description Email verified; workspace shell created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingVerifyEmailResponse"];
                };
            };
        };
    };
    onboardingVerifyEmailLink: {
        parameters: {
            query: {
                token: string;
                /** @description When true, redirect to app deep link instead of JSON */
                redirect?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Magic link verified; same body as email verify */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingVerifyEmailResponse"];
                };
            };
            /** @description Redirect to app deep link (redirect=true or Accept text/html) */
            302: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    onboardingRequestPhoneOtp: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingRequestPhoneOtpRequest"];
            };
        };
        responses: {
            /** @description SMS OTP dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingSentResponse"];
                };
            };
        };
    };
    onboardingVerifyPhone: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingVerifyPhoneRequest"];
            };
        };
        responses: {
            /** @description Phone verified; keeper user created */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingVerifyPhoneResponse"];
                };
            };
        };
    };
    onboardingDeviceVerifyRequestPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingDeviceVerifyRequest"];
            };
        };
        responses: {
            /** @description Push dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceVerifySentResponse"];
                };
            };
        };
    };
    onboardingDeviceVerifyResendPush: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingDeviceVerifyRequest"];
            };
        };
        responses: {
            /** @description Push resent */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceVerifySentResponse"];
                };
            };
        };
    };
    onboardingDeviceVerifyRequestSms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingDeviceVerifySmsRequest"];
            };
        };
        responses: {
            /** @description Opt-in SMS dispatched */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceVerifySentResponse"];
                };
            };
        };
    };
    onboardingDeviceVerifyVerifySms: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingDeviceVerifySmsConfirmRequest"];
            };
        };
        responses: {
            /** @description SMS verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeviceVerifySessionResponse"];
                };
            };
        };
    };
    onboardingDeviceVerifyLink: {
        parameters: {
            query: {
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deep link verified */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingDeviceVerifyLinkResponse"];
                };
            };
        };
    };
    onboardingConfirmDevice: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingConfirmDeviceRequest"];
            };
        };
        responses: {
            /** @description Device gate passed; userRefresh issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingConfirmDeviceResponse"];
                };
            };
        };
    };
    onboardingSetupPassword: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingSetupPasswordRequest"];
            };
        };
        responses: {
            /** @description Workspace password set; family session issued */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingSetupPasswordResponse"];
                };
            };
        };
    };
    onboardingFinalizeWorkspace: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OnboardingFinalizeWorkspaceRequest"];
            };
        };
        responses: {
            /** @description Final workspace slug chosen */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OnboardingFinalizeWorkspaceResponse"];
                };
            };
            409: components["responses"]["Error"];
        };
    };
    tokenRefresh: {
        parameters: {
            query?: never;
            header?: {
                "X-Scope"?: components["parameters"]["XScope"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TokenRefreshRequest"];
            };
        };
        responses: {
            /** @description New tokens */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyTokenBundle"] | components["schemas"]["UserRefreshResponse"];
                };
            };
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["LogoutRequest"];
            };
        };
        responses: {
            /** @description Logged out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OkResponse"];
                };
            };
        };
    };
    pairResolve: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairResolveRequest"];
            };
        };
        responses: {
            /** @description Family preview */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairingResolveResult"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    pairConfirm: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairConfirmRequest"];
            };
        };
        responses: {
            /** @description Pending or session */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PairConfirmPending"] | components["schemas"]["AuthSessionResponse"];
                };
            };
        };
    };
    pairApprovalStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApprovalStatusRequest"];
            };
        };
        responses: {
            /** @description Status */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalPending"] | components["schemas"]["ApprovalApproved"] | components["schemas"]["ApprovalRejected"];
                };
            };
        };
    };
    pairReject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRejectRequest"];
            };
        };
        responses: {
            /** @description Rejected */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApprovalRejected"];
                };
            };
        };
    };
    pairApprove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PairRejectRequest"];
            };
        };
        responses: {
            /** @description Approved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {string} */
                        status: "approved";
                    };
                };
            };
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMeRequest"];
            };
        };
        responses: {
            /** @description Updated profile */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    uploadAvatar: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            /** @description Profile with placeholder avatarUrl */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserProfile"];
                };
            };
        };
    };
    createFamily: {
        parameters: {
            query?: never;
            header?: {
                /** @description Optional client key; replays cached 201 response for 24h (AUTH-022) */
                "Idempotency-Key"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateFamilyRequest"];
            };
        };
        responses: {
            /** @description Family created with session */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CreateFamilyResponse"];
                };
            };
        };
    };
    listUserFamilies: {
        parameters: {
            query?: {
                page?: number;
                limit?: number;
                sync?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Family list or sync delta */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FamilyListResponse"] | components["schemas"]["FamilySyncResponse"];
                };
            };
        };
    };
}
